services:
  application:
    container_name: application
    build:
      context: ..
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9005:9000"
    volumes:
      - ../application:/var/www/html
    depends_on:
      - database
    networks:
      - application_network
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "7070:80"
    volumes:
      - ../application:/var/www/html
      - ../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application
    networks:
      - application_network
  database:
    platform: linux/amd64
    container_name: database
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: applicationDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3312:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    networks:
      - application_network
networks:
  application_network:

